version: '2.0'

services:
  slides:
    image: kcmastrpc/remarkjs:1.0
    volumes:
      - ./index.html.tmpl:/index.html.tmpl
      - ./slides:/usr/share/nginx/html/slides
    environment:
      - DEV_MODE=true
      - TITLE=Docker Nashville Meetup
      - HIGHLIGHT_LINES=true
      - HIGHLIGHT_SPANS=true
      - RATIO=16:9
    ports:
      - 8080:80